// Generated by IDAStruct_To_CHeader.py
#pragma once
#include <windows.h>


#pragma pack(push, 1)
struct SImgGTAItemInfo	// sizeof = 0x14
{
	DWORD hash;
	WORD unk1;
	BYTE loadingState;
	BYTE imgID;
	DWORD blockOffset;
	DWORD blockCount;
	BYTE State;
	BYTE field_11[3];
};
#pragma pack(pop)

static_assert(sizeof(SImgGTAItemInfo) == 0x14, "Incorrect struct size: SImgGTAItemInfo");